// @ts-check
/**
 * Build the Next.js standalone server into a self-contained directory
 * that Tauri can ship as a `bundle.resources` payload.
 *
 * Output layout (relative to `apps/desktop/`):
 *
 *   sidecar/
 *     server/                 (full standalone server, including static + public)
 *       server.js             (Next.js entry)
 *       node_modules/...
 *       .next/static/...
 *       public/...
 *     launcher.mjs            (boots server.js, prints "READY <port>")
 *     manifest.json           (build metadata)
 *
 * The launcher is plain ESM so it can run on whatever `node` the user has
 * on PATH at runtime. Packaging Node itself into a single executable
 * (Node SEA / @yao-pkg/pkg) is deliberately deferred — the libsql native
 * bindings under `@libsql/client/native` need extra plumbing that is not
 * worth attempting until the dev workflow is fully validated.
 */
import { execSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const desktopDir = path.resolve(__dirname, "..");
const repoRoot = path.resolve(desktopDir, "..", "..");
const webDir = path.join(repoRoot, "apps", "web");
const standaloneDir = path.join(webDir, ".next", "standalone");
const staticDir = path.join(webDir, ".next", "static");
const publicDir = path.join(webDir, "public");

const sidecarRoot = path.join(desktopDir, "sidecar");
const sidecarServer = path.join(sidecarRoot, "server");

console.log("[build-sidecar] step 1/4: building @wrackspurt/web (standalone)");
execSync("pnpm --filter @wrackspurt/web build", {
  stdio: "inherit",
  cwd: repoRoot,
});

if (!existsSync(standaloneDir)) {
  console.error(
    `[build-sidecar] expected ${standaloneDir} after build but it is missing — is next.config.mjs's output:"standalone" still set?`,
  );
  process.exit(1);
}

console.log("[build-sidecar] step 2/4: clearing previous sidecar/");
rmSync(sidecarRoot, { recursive: true, force: true });
mkdirSync(sidecarServer, { recursive: true });

console.log("[build-sidecar] step 3/4: copying standalone tree");
cpSync(standaloneDir, sidecarServer, { recursive: true });

// Next emits the standalone server alongside an *empty* `apps/web/.next`
// inside `<standalone>/apps/web/.next` — we must layer the static assets
// in there so the running server can find them.
const innerWebNextStatic = path.join(
  sidecarServer,
  "apps",
  "web",
  ".next",
  "static",
);
if (existsSync(staticDir)) {
  mkdirSync(innerWebNextStatic, { recursive: true });
  cpSync(staticDir, innerWebNextStatic, { recursive: true });
}
const innerWebPublic = path.join(sidecarServer, "apps", "web", "public");
if (existsSync(publicDir)) {
  mkdirSync(innerWebPublic, { recursive: true });
  cpSync(publicDir, innerWebPublic, { recursive: true });
}

console.log("[build-sidecar] step 4/4: writing launcher + manifest");

const launcher = `#!/usr/bin/env node
// Auto-generated by apps/desktop/scripts/build-sidecar.mjs.
// This launcher is invoked by the Tauri shell (see apps/desktop/src-tauri/src/sidecar.rs)
// in production builds. It picks a free port, sets the Next.js env vars,
// runs server.js, and only emits READY once /api/doctor responds — so the
// shell doesn't navigate to a half-booted app.
import { createServer } from "node:net";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const desiredPort = Number.parseInt(process.env.WRACKSPURT_PORT ?? "0", 10) || 0;
const HEALTH_TIMEOUT_MS = Number.parseInt(
  process.env.WRACKSPURT_HEALTH_TIMEOUT_MS ?? "30000",
  10,
);

async function pickPort(start) {
  return await new Promise((resolve, reject) => {
    const srv = createServer();
    srv.unref();
    srv.on("error", reject);
    srv.listen(start, "127.0.0.1", () => {
      const address = srv.address();
      const port = typeof address === "object" && address ? address.port : start;
      srv.close(() => resolve(port));
    });
  });
}

async function waitForHealth(url, deadline) {
  while (Date.now() < deadline) {
    try {
      const r = await fetch(url, { signal: AbortSignal.timeout(2000) });
      // Any 2xx/4xx response means the HTTP server itself is up, which
      // is what we actually need to gate the webview navigation on.
      if (r.status >= 200 && r.status < 500) return true;
    } catch {
      /* not up yet */
    }
    await new Promise((r) => setTimeout(r, 250));
  }
  return false;
}

const port = await pickPort(desiredPort);
process.env.PORT = String(port);
process.env.HOSTNAME = "127.0.0.1";
process.env.WRACKSPURT_DB_PATH ??= path.join(__dirname, "data", "wrackspurt.db");

// Boot Next first (don't await — server.js binds the socket and keeps the
// event loop alive), then probe /api/settings before announcing READY.
const bootPromise = import(
  path.join(__dirname, "server", "apps", "web", "server.js")
);

const url = \`http://127.0.0.1:\${port}\`;
const ready = await waitForHealth(\`\${url}/api/settings\`, Date.now() + HEALTH_TIMEOUT_MS);
if (!ready) {
  process.stderr.write(
    \`[launcher] health probe at \${url}/api/settings timed out after \${HEALTH_TIMEOUT_MS}ms\\n\`,
  );
  // Still emit READY so the shell at least navigates — the user can
  // retry from the UI.
}
process.stdout.write(\`READY \${url}\\n\`);

await bootPromise;
`;
writeFileSync(path.join(sidecarRoot, "launcher.mjs"), launcher, {
  mode: 0o755,
});

const manifest = {
  generatedAt: new Date().toISOString(),
  serverEntry: "server/apps/web/server.js",
  launcher: "launcher.mjs",
  notes:
    "Spawned via tauri-plugin-shell with `node` on PATH. Single-binary Node SEA packaging is deferred (libsql native bindings).",
};
writeFileSync(
  path.join(sidecarRoot, "manifest.json"),
  JSON.stringify(manifest, null, 2),
);

console.log(
  `[build-sidecar] done -> ${path.relative(repoRoot, sidecarRoot)}/{server,launcher.mjs,manifest.json}`,
);
